### ISSUE TITLE
Raspberry Pi Zero ARMv6 - Linking target lc0

### ISSUE THREAD

**Issue by mickkn** [LeelaChessZero/lc0#1551]
Shouldn't be possible to build on a Raspberry Pi Zero?

Using: CC=gcc-8 CXX=g++-8 ./build.sh -Ddefault_library=static -Db_lto=false -Dgtest=false

[57/57] Linking target lc0
FAILED: lc0
g++-8  -o lc0 lc0.p/src_main.cc.o lc0.p/src_utils_protomessage.cc.o lc0.p/src_engine.cc.o lc0.p/src_version.cc.o lc0.p/src_benchmark_backendbench.cc.o lc0.p/src_benchmark_benchmark.cc.o lc0.p/src_chess_bitboard.cc.o lc0.p/src_chess_board.cc.o lc0.p/src_chess_position.cc.o lc0.p/src_chess_uciloop.cc.o lc0.p/src_mcts_node.cc.o lc0.p/src_mcts_params.cc.o lc0.p/src_mcts_search.cc.o lc0.p/src_mcts_stoppers_common.cc.o lc0.p/src_mcts_stoppers_factory.cc.o lc0.p/src_mcts_stoppers_legacy.cc.o lc0.p/src_mcts_stoppers_alphazero.cc.o lc0.p/src_mcts_stoppers_smooth.cc.o lc0.p/src_mcts_stoppers_stoppers.cc.o lc0.p/src_mcts_stoppers_timemgr.cc.o lc0.p/src_neural_cache.cc.o lc0.p/src_neural_encoder.cc.o lc0.p/src_neural_factory.cc.o lc0.p/src_neural_loader.cc.o lc0.p/src_neural_network_check.cc.o lc0.p/src_neural_network_demux.cc.o lc0.p/src_neural_network_legacy.cc.o lc0.p/src_neural_network_mux.cc.o lc0.p/src_neural_network_random.cc.o lc0.p/src_neural_network_record.cc.o lc0.p/src_neural_network_rr.cc.o lc0.p/src_neural_writer.cc.o lc0.p/src_selfplay_game.cc.o lc0.p/src_selfplay_loop.cc.o lc0.p/src_selfplay_tournament.cc.o lc0.p/src_syzygy_syzygy.cc.o lc0.p/src_utils_commandline.cc.o lc0.p/src_utils_configfile.cc.o lc0.p/src_utils_esc_codes.cc.o lc0.p/src_utils_histogram.cc.o lc0.p/src_utils_logging.cc.o lc0.p/src_utils_numa.cc.o lc0.p/src_utils_optionsdict.cc.o lc0.p/src_utils_optionsparser.cc.o lc0.p/src_utils_random.cc.o lc0.p/src_utils_string.cc.o lc0.p/src_utils_weights_adapter.cc.o lc0.p/src_utils_filesystem.posix.cc.o lc0.p/src_neural_blas_convolution1.cc.o lc0.p/src_neural_blas_fully_connected_layer.cc.o lc0.p/src_neural_blas_se_unit.cc.o lc0.p/src_neural_blas_network_blas.cc.o lc0.p/src_neural_blas_winograd_convolution3.cc.o lc0.p/src_neural_shared_activation.cc.o lc0.p/src_neural_shared_winograd_filter.cc.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -mfpu=neon -pthread -Wl,--start-group /usr/lib/libopenblas.so /usr/lib/arm-linux-gnueabihf/libz.so /usr/lib/gcc/arm-linux-gnueabihf/8/libatomic.so -Wl,--end-group
/usr/bin/ld: lc0.p/src_neural_blas_convolution1.cc.o: in function `lczero::Convolution1<false>::Forward(unsigned int, unsigned int, unsigned int, float const*, float const*, float*)':
convolution1.cc:(.text+0x2994): undefined reference to `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)'
/usr/bin/ld: lc0.p/src_neural_blas_fully_connected_layer.cc.o: in function `lczero::FullyConnectedLayer<false>::Forward1D(unsigned int, unsigned int, unsigned int, float const*, float const*, float const*, bool, float*)':
fully_connected_layer.cc:(.text+0x2e04): undefined reference to `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)'
/usr/bin/ld: fully_connected_layer.cc:(.text+0x2f0c): undefined reference to `cblas_sgemv(CBLAS_ORDER, CBLAS_TRANSPOSE, int, int, float, float const*, int, float const*, int, float, float*, int)'
/usr/bin/ld: lc0.p/src_neural_blas_fully_connected_layer.cc.o: in function `lczero::FullyConnectedLayer<false>::Forward0D(unsigned int, float const*, float const*)':
fully_connected_layer.cc:(.text+0x2f38): undefined reference to `cblas_sdot(int, float const*, int, float const*, int)'
/usr/bin/ld: lc0.p/src_neural_blas_winograd_convolution3.cc.o: in function `lczero::WinogradConvolution3<false>::Sgemm(unsigned int, float const*, unsigned int, unsigned int)':
winograd_convolution3.cc:(.text+0x29bc): undefined reference to `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)'
/usr/bin/ld: lc0.p/src_neural_blas_winograd_convolution3.cc.o: in function `lczero::WinogradConvolution3<false>::Forward(unsigned int, unsigned int, unsigned int, float const*, float const*, float*)':
winograd_convolution3.cc:(.text._ZN6lczero20WinogradConvolution3ILb0EE7ForwardEjjjPKfS3_Pf[_ZN6lczero20WinogradConvolution3ILb0EE7ForwardEjjjPKfS3_Pf]+0xb8): undefined reference to `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by mickkn** [comment]
Managed to build the 0.27 release but this error:

`pi@mchessboard:~/lc0-0.27.0/build/release $ ./lc0
Illegal instruction`

**Comment by andber1** [comment]
I also tried to run lc0 on a Raspberry Pi Zero. Compilation works fine with version 0.28.2 and ggc-8. However, I got the same error as mickkn when executing lc0:
`Illegal instruction`
@mickkn Did you find a solution?

BTW: The steps described [here](https://github.com/LeelaChessZero/lc0#raspberry-pi) did not work for me. I got the error:
`/usr/bin/ld: liblc0_lib.a: error adding symbols: archive has no index; run ranlib to add one`
Solution was to use gcc-8.

**Comment by mickkn** [comment]
Nah, didn’t solve it. I’m using Minic and Stockfish in my project https://github.com/mickkn/mChessBoard the executables are in the sorce folder

**Comment by andber1** [comment]
Apparently the neon instructions are illegal on armv6. Compilation works with the following command:
`./build.sh -Dneon=false`

**Comment by andber1** [comment]
I also got segmentation faults with clang. Using gcc-8 helps.
